=== gjgress/G-RIPS-2022-Mitsubishi-A/Code/map-matching-dataset/metadata.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:attributeGroup name="spat-mism">
    <xs:attribute name="max" type="xs:double" use="required"/>
    <xs:attribute name="mad" type="xs:double" use="required"/>  
  </xs:attributeGroup>
  <xs:attributeGroup name="file">
    <xs:attribute name="path" type="xs:string" use="required"/>
    <xs:attribute name="md5" type="xs:string" use="required"/>  
  </xs:attributeGroup>
  <xs:element name="records">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
	<xs:element name="record">
	  <xs:complexType>  
            <xs:sequence>    
	      <xs:element name="track" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:attributeGroup ref="file"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="nodes" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:attributeGroup ref="file"/>
                </xs:complexType> 
              </xs:element>
              <xs:element name="arcs" minOccurs="1"  maxOccurs="1">
                <xs:complexType>
                  <xs:attributeGroup ref="file"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="route" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:attributeGroup ref="file"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="spatial-mismatch" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:attributeGroup ref="spat-mism"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="tag" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="key" type="xs:string" use="required"/>
                  <xs:attribute name="value" type="xs:string" use="required"/>  
                </xs:complexType> 
              </xs:element>     
	    </xs:sequence>
	    <xs:attribute name="id" type="xs:nonNegativeInteger" use="required"/>
	    <xs:attribute name="state"> 
	      <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="revised"/>
                  <xs:enumeration value="corrected"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute> 
	  </xs:complexType>    
	</xs:element>
      </xs:choice>  
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gjgress/G-RIPS-2022-Mitsubishi-A/Code/Data/map-matching-dataset/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<records xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="metadata.xsd"><record id="0" state="revised"><track path="./00000000/00000000.track" md5="c96662670150ddeacc47979baf4100e1"/><nodes path="./00000000/00000000.nodes" md5="4f981ece3815f07ecaf3ee52166bb185"/><arcs path="./00000000/00000000.arcs" md5="b9939d45c90ef29deb8813fb80c7175a"/><route path="./00000000/00000000.route" md5="fa5cc744911bece28a71e9b3594d1a8e"/><spatial-mismatch mad="2.64576322" max="21.79630303"/><tag key="feature" value="gaps"/></record><record id="1" state="revised"><track path="./00000001/00000001.track" md5="5df6ad7363083896be8e821a6ce351b2"/><nodes path="./00000001/00000001.nodes" md5="4fe3de9c442ed7fe0fbd421a80b4e470"/><arcs path="./00000001/00000001.arcs" md5="06a522a1afd092e1cc4630609e996a98"/><route path="./00000001/00000001.route" md5="83e027a97a8ed06239d167836ae7f3e4"/><spatial-mismatch mad="1.43454499" max="9.85943094"/><tag key="feature" value="gaps"/></record><record id="2" state="revised"><track path="./00000002/00000002.track" md5="ec159d81eb30505b5f8bf505642f0bde"/><nodes path="./00000002/00000002.nodes" md5="0020d2aec1c3280c8cdd89d67c5eba8c"/><arcs path="./00000002/00000002.arcs" md5="f0aa36a4ff42be77034ce87a08b933bf"/><route path="./00000002/00000002.route" md5="04fcf3733330ab3eff34b1f0722036fa"/><spatial-mismatch mad="2.44117243" max="557.26251640"/><tag key="feature" value="gaps"/><tag key="feature" value="congruence-issues"/></record><record id="3" state="revised"><track path="./00000003/00000003.track" md5="ac6a89313df7d4c5fd0d903832e72b46"/><nodes path="./00000003/00000003.nodes" md5="ee64939d0ecaf28ae54fce753b37fd39"/><arcs path="./00000003/00000003.arcs" md5="ca02a8f59463dc4e00fdee027389d313"/><route path="./00000003/00000003.route" md5="b56725aac8ff75636a89ad1b520cd4a6"/><spatial-mismatch mad="1.64818533" max="19.81368539"/></record><record id="4" state="revised"><track path="./00000004/00000004.track" md5="f85410ca4760e4ecb5ac1f8fd0a2fd3f"/><nodes path="./00000004/00000004.nodes" md5="2fb93e40ecb643d459126a55984cffe4"/><arcs path="./00000004/00000004.arcs" md5="cf2e02346d1151f1f6a77b3774136489"/><route path="./00000004/00000004.route" md5="3203849f3496aba25683259d64fd3dd6"/><spatial-mismatch mad="5.78902435" max="37.51766980"/><tag key="feature" value="gaps"/><tag key="feature" value="u-turns"/></record><record id="5" state="revised"><track path="./00000005/00000005.track" md5="71e3fa719ab5cb05b2bcfe01f1f2c8f4"/><nodes path="./00000005/00000005.nodes" md5="b232ece830d4b0bd707e2bcb90b2aa22"/><arcs path="./00000005/00000005.arcs" md5="02e5b450c733e4daecd1e43879805a92"/><route path="./00000005/00000005.route" md5="7ecc39bbc8344f6d335c6a703b67378e"/><spatial-mismatch mad="1.66206622" max="18.96028687"/></record><record id="6" state="revised"><track path="./00000006/00000006.track" md5="102fbe2b034da248c736d3b585e52f63"/><nodes path="./00000006/00000006.nodes" md5="6f5dfd2e76fd9a876a889208137534fc"/><arcs path="./00000006/00000006.arcs" md5="00928b2882267ab301e406c807e28c8f"/><route path="./00000006/00000006.route" md5="aea4151789be26626d418b9cb6a26c34"/><spatial-mismatch mad="2.00938491" max="17.61929657"/><tag key="feature" value="gaps"/><tag key="feature" value="u-turns"/></record><record id="7" state="revised"><track path="./00000007/00000007.track" md5="f956efe8bff19693bc3819409c179d40"/><nodes path="./00000007/00000007.nodes" md5="3cb2ef39bc24126f0bd6f74a6d89c6de"/><arcs path="./00000007/00000007.arcs" md5="5c45f069cf6a5d9258fafcd4876564d9"/><route path="./00000007/00000007.route" md5="e411458f5b50d9cb648c4628b9a26c54"/><spatial-mismatch mad="1.80597564" max="25.08344397"/></record><record id="8" state="revised"><track path="./00000008/00000008.track" md5="17be1236ad8a0c0134d098ecfcf355c8"/><nodes path="./00000008/00000008.nodes" md5="3a3c4ed8e4a13286ca18d68c0a06dec3"/><arcs path="./00000008/00000008.arcs" md5="a6beaebcd88d292980873e764542ee08"/><route path="./00000008/00000008.route" md5="5cc9cf603e5145f6d36a83009e30fbde"/><spatial-mismatch mad="3.79536632" max="72.30031651"/><tag key="feature" value="gaps"/><tag key="feature" value="loops"/><tag key="feature" value="u-turns"/><tag key="feature" value="congruence-issues"/></record><record id="9" state="revised"><track path="./00000009/00000009.track" md5="fea519d3f108d3de1f7208a32c558288"/><nodes path="./00000009/00000009.nodes" md5="47136a1d59c538f9ca3efcdd0ca28fd1"/><arcs path="./00000009/00000009.arcs" md5="422699d481f07856eeb0148bdfca6703"/><route path="./00000009/00000009.route" md5="1a4736364894abe502e1a10ac666ae31"/><spatial-mismatch mad="2.00556185" max="36.65832532"/><tag key="feature" value="gaps"/></record><record id="10" state="revised"><track path="./00000010/00000010.track" md5="4cf1ab999f3ed9d4034a30c3dfce477c"/><nodes path="./00000010/00000010.nodes" md5="9d1264bc2b396f5e8d27a4f5b09147cc"/><arcs path="./00000010/00000010.arcs" md5="184fbf98455a286af0a1cdd146fb96cf"/><route path="./00000010/00000010.route" md5="0528ff00d892df57ae4d9f1a6fa7d387"/><spatial-mismatch mad="1.85014565" max="31.95606583"/></record><record id="11" state="revised"><track path="./00000011/00000011.track" md5="da06fae3977f5d73968fc1fcd0cf8fbf"/><nodes path="./00000011/00000011.nodes" md5="bb825d98c5eab30c1d741f9bbd80d466"/><arcs path="./00000011/00000011.arcs" md5="9d2cfa2d4f8f00c937c14863f06b93be"/><route path="./00000011/00000011.route" md5="110552ca4a14951bfd68ff2c2f38f499"/><spatial-mismatch mad="2.49709874" max="15.35710382"/><tag key="feature" value="gaps"/><tag key="feature" value="u-turns"/></record><record id="12" state="revised"><track path="./00000012/00000012.track" md5="3162a6451967ca503b7ca2f81e285202"/><nodes path="./00000012/00000012.nodes" md5="f67fa56760bb6b96d82fd74c62488403"/><arcs path="./00000012/00000012.arcs" md5="8d951c2483d25998fdf66fa888bd2ebc"/><route path="./00000012/00000012.route" md5="22f97f5ac625a312455c2cb0d1e2cfd7"/><spatial-mismatch mad="1.92617865" max="20.17982171"/><tag key="feature" value="gaps"/></record><record id="13" state="revised"><track path="./00000013/00000013.track" md5="9d7a813c0a2da2115f9ebbd3d43bc058"/><nodes path="./00000013/00000013.nodes" md5="fc1b8cbeab7b80cfcf34a4cb2283167c"/><arcs path="./00000013/00000013.arcs" md5="18a59de86f5d34e9bab59cc1f07c0849"/><route path="./00000013/00000013.route" md5="e46ef1ef2e8deb90ebe964e9e5d4bae6"/><spatial-mismatch mad="1.52604613" max="19.23281947"/><tag key="feature" value="gaps"/></record><record id="14" state="revised"><track path="./00000014/00000014.track" md5="a10fecff3ebb1b8ead8397bc66aa496a"/><nodes path="./00000014/00000014.nodes" md5="72fd481f30918b857ecdde4036776515"/><arcs path="./00000014/00000014.arcs" md5="652081eb77b8722b4454f409eb78404d"/><route path="./00000014/00000014.route" md5="9da0a7043ae03cf5c49823e0f5279578"/><spatial-mismatch mad="1.70160544" max="39.95653449"/><tag key="feature" value="gaps"/><tag key="feature" value="loops"/></record><record id="15" state="revised"><track path="./00000015/00000015.track" md5="bb6d079fde7afabb0196d60c4d14f819"/><nodes path="./00000015/00000015.nodes" md5="7ff8b480635db207bd13dc930d92c71f"/><arcs path="./00000015/00000015.arcs" md5="6d77cd7d35763e679c9105e7410d5e0b"/><route path="./00000015/00000015.route" md5="1ed4189e5fc4bd7221f06e6662ef32c1"/><spatial-mismatch mad="2.71628993" max="55.20113169"/><tag key="feature" value="congruence-issues"/></record><record id="16" state="revised"><track path="./00000016/00000016.track" md5="58dadd6ca37e64a707a72d525194d364"/><nodes path="./00000016/00000016.nodes" md5="64ff97153a36d58bd6dcdbae13825408"/><arcs path="./00000016/00000016.arcs" md5="2e0f9cfcf1812eea3dd1b070b736d8dc"/><route path="./00000016/00000016.route" md5="4529edb2741717d50c6355d066dc2229"/><spatial-mismatch mad="2.10814687" max="32.87812790"/><tag key="feature" value="u-turns"/><tag key="feature" value="congruence-issues"/></record><record id="17" state="revised"><track path="./00000017/00000017.track" md5="0fb0e3cf920cd0b83cfd09863dbf8530"/><nodes path="./00000017/00000017.nodes" md5="3c588998cced0f1ee1ce9d1f58ddb420"/><arcs path="./00000017/00000017.arcs" md5="2e13b4ba3be23dac62372f620b262ce6"/><route path="./00000017/00000017.route" md5="60001cb726243050d88615ac3fe0a631"/><spatial-mismatch mad="2.02055845" max="15.82861833"/><tag key="feature" value="gaps"/><tag key="feature" value="loops"/></record><record id="18" state="revised"><track path="./00000018/00000018.track" md5="26904efe3c542a8784b47c755bfaa5f0"/><nodes path="./00000018/00000018.nodes" md5="714456a69355b71128115d44e8abf879"/><arcs path="./00000018/00000018.arcs" md5="10b4b9d6150ea514729b703a3dd152de"/><route path="./00000018/00000018.route" md5="48963d82155c6c80cefab82540904203"/><spatial-mismatch mad="1.19192864" max="10.33131209"/><tag key="feature" value="gaps"/><tag key="feature" value="loops"/></record><record id="19" state="revised"><track path="./00000019/00000019.track" md5="e8c079baf00cf45dd6836050834466c2"/><nodes path="./00000019/00000019.nodes" md5="3a2585c70512a446a24fe147402f86a1"/><arcs path="./00000019/00000019.arcs" md5="4df4627f0f714699b5fa7e6cfca14d10"/><route path="./00000019/00000019.route" md5="74b6047bb0245adf284ef741de36bc4e"/><spatial-mismatch mad="1.82258234" max="291.39662446"/><tag key="feature" value="congruence-issues"/></record><record id="20" state="revised"><track path="./00000020/00000020.track" md5="68786f1b29b72ff10a929cef1c852941"/><nodes path="./00000020/00000020.nodes" md5="c9b5f5970a3012041a0b6a9fca38cbe1"/><arcs path="./00000020/00000020.arcs" md5="02e9248cde65b2947882f94ae59b3581"/><route path="./00000020/00000020.route" md5="742094eb0b43428346e0f93fa2b220fa"/><spatial-mismatch mad="2.14408731" max="150.63885312"/></record><record id="21" state="revised"><track path="./00000021/00000021.track" md5="4170093cb7099c4ad0547abf7103741d"/><nodes path="./00000021/00000021.nodes" md5="346c256dbaabcb450972532301aec1dd"/><arcs path="./0000002
